DROP TABLE IF EXISTS `series_participants_winterblast`;
CREATE TABLE `series_participants_winterblast` (
  `id` int(4) NOT NULL AUTO_INCREMENT,
  `seriesId` int(4),
  `participantName` varchar(128),
  `age` int(4),
  `sex` char(3),
  `division` varchar(32) default '',
  `race1Points` decimal(8,2) default 0.0,
  `race1Time` varchar(32) default '',
  `race2Points` decimal(8,2) default 0.0,
  `race2Time` varchar(32) default '',
  `race3Points` decimal(8,2) default 0.0,
  `race3Time` varchar(32) default '',
  `race4Points` decimal(8,2) default 0.0,
  `race4Time` varchar(32) default '',
  `race5Points` decimal(8,2) default 0.0,
  `race5Time` varchar(32) default '',
  `race6Points` decimal(8,2) default 0.0,
  `race6Time` varchar(32) default '',
  `race7Points` decimal(8,2) default 0.0,
  `race7Time` varchar(32) default '',
  `race8Points` decimal(8,2) default 0.0,
  `race8Time` varchar(32) default '',
  `race9Points` decimal(8,2) default 0.0,
  `race9Time` varchar(32) default '',
  `race10Points` decimal(8,2) default 0.0,
  `race10Time` varchar(32) default '',
  `totalPoints1` decimal(8,2) default 0.0,
  `totalPoints2` decimal(8,2) default 0.0,
  `overallPlace1` int(4) default 0,
  `overallPlace2` int(4) default 0,
  `divisionPlace1` int(4) default 0,
  `divisionPlace2` int(4) default 0,
  `totalRaces1` int(4) default 0,
  `totalRaces2` int(4) default 0,
  `bestText` varchar(1024) default '',
  `bestPoints` decimal(8,2) default 0.0,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;
